"""Identity and access model.

This is the part of the schema that did not exist before revision ``0002``:
until then identity lived in ``backend/data/user_state.json`` -- a single file
rewritten in full on every login, with no constraints, no transactions and no
referential integrity.

The access chain implemented on top of these tables is

    role -> permission -> ownership -> tenant -> scope -> licence -> flag ->
    publication status

and deny always wins. Each link is a real table with real constraints, so a
missing link is a failed foreign key rather than a missing ``if``.

Design decisions worth keeping in mind when extending this module:

* ``users.user_id`` stays ``text``. Production already carries opaque ids
  (``u_invite_001122``, ``admin_console``) in ten tables and in issued JWTs;
  swapping them for UUIDs would invalidate every live session and every stored
  reference for no functional gain.
* Identifiers (login / phone / e-mail) are rows, not columns: four accounts
  already have two logins each, and a column cannot hold that.
* Passwords are Argon2id for anything set from now on. The two legacy families
  (bcrypt, pbkdf2_sha256) are preserved as-is and marked ``needs_rehash`` so the
  next successful login upgrades them; nobody is locked out by the migration.
* ``audit_log`` and ``auth_attempt_events`` are append-only, enforced by a
  trigger in the database rather than by convention in the service layer.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

TZ = DateTime(timezone=True)

# Generated by pgcrypto, which is already installed in production.
_UUID_PK = text("gen_random_uuid()")

__all__ = [
    "AuditLogEntry",
    "AuthAttemptEvent",
    "AuthLockout",
    "Consent",
    "FeatureFlag",
    "FeatureFlagOverride",
    "OtpChallenge",
    "ParentChildLink",
    "Permission",
    "RefreshToken",
    "Role",
    "RoleAssignment",
    "RolePermission",
    "User",
    "UserAppState",
    "UserCredential",
    "UserEntitlement",
    "UserEntitlementItem",
    "UserIdentifier",
    "UserSession",
]

# --------------------------------------------------------------------------- #
# Vocabularies. Kept as module constants so the CHECK constraints below, the
# seed data in the migration and the service layer cannot drift apart.
# --------------------------------------------------------------------------- #

USER_STATUSES = ("active", "suspended", "deleted")
IDENTIFIER_KINDS = ("login", "phone", "email")
PASSWORD_ALGORITHMS = ("argon2id", "bcrypt", "pbkdf2_sha256")
PERMISSION_EFFECTS = ("allow", "deny")
SCOPE_TYPES = ("global", "organization", "school", "site", "class")
FLAG_SCOPE_TYPES = ("global", "organization", "school", "site", "class", "user")
CONSENT_TYPES = ("terms", "privacy", "personal_data", "parent_approval", "marketing")
LINK_STATUSES = ("pending", "confirmed", "revoked")
ENTITLEMENT_KINDS = ("plan", "module", "feature")
ENTITLEMENT_SOURCES = ("grant", "manual", "trial", "legacy")
AUDIT_RESULTS = ("ok", "denied", "failed")


def _in_list(column: str, values: tuple[str, ...]) -> str:
    rendered = ", ".join(f"'{value}'::text" for value in values)
    return f"{column} = ANY (ARRAY[{rendered}])"


# --------------------------------------------------------------------------- #
# Identity
# --------------------------------------------------------------------------- #


class User(Base):
    """A person with an account. The single source of identity truth."""

    __tablename__ = "users"

    user_id: Mapped[str] = mapped_column(Text, primary_key=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'active'"))
    display_name: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    is_demo: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    is_test: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())
    last_login_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    deleted_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)

    identifiers: Mapped[list["UserIdentifier"]] = relationship(
        back_populates="user", cascade="all, delete-orphan", passive_deletes=True
    )
    credential: Mapped[Optional["UserCredential"]] = relationship(
        back_populates="user", cascade="all, delete-orphan", passive_deletes=True, uselist=False
    )
    sessions: Mapped[list["UserSession"]] = relationship(
        back_populates="user", cascade="all, delete-orphan", passive_deletes=True
    )
    role_assignments: Mapped[list["RoleAssignment"]] = relationship(
        back_populates="user", cascade="all, delete-orphan", passive_deletes=True
    )
    consents: Mapped[list["Consent"]] = relationship(
        back_populates="user",
        cascade="all, delete-orphan",
        passive_deletes=True,
        foreign_keys="Consent.user_id",
    )

    __table_args__ = (
        CheckConstraint(_in_list("status", USER_STATUSES), name="users_status_check"),
        CheckConstraint(
            "(status <> 'deleted'::text) OR (deleted_at IS NOT NULL)",
            name="users_deleted_at_check",
        ),
        Index("idx_users_status", "status"),
    )


class UserIdentifier(Base):
    """A login, phone number or e-mail address that resolves to one account.

    ``value_normalized`` is what uniqueness is enforced on: logins lower-cased,
    phones reduced to digits with a leading ``+``. ``value`` keeps what the user
    actually typed.
    """

    __tablename__ = "user_identifiers"

    identifier_id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, server_default=_UUID_PK)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    value: Mapped[str] = mapped_column(Text, nullable=False)
    value_normalized: Mapped[str] = mapped_column(Text, nullable=False)
    is_primary: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    verified_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    user: Mapped["User"] = relationship(back_populates="identifiers")

    __table_args__ = (
        CheckConstraint(_in_list("kind", IDENTIFIER_KINDS), name="user_identifiers_kind_check"),
        UniqueConstraint("kind", "value_normalized", name="uq_user_identifiers_kind_value"),
        Index("idx_user_identifiers_user", "user_id"),
        Index(
            "uq_user_identifiers_primary",
            "user_id",
            "kind",
            unique=True,
            postgresql_where=text("is_primary"),
        ),
    )


class UserCredential(Base):
    """Password material. One row per account, or none for passwordless users."""

    __tablename__ = "user_credentials"

    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), primary_key=True
    )
    algorithm: Mapped[str] = mapped_column(Text, nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    needs_rehash: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    must_change: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    updated_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    user: Mapped["User"] = relationship(back_populates="credential")

    __table_args__ = (
        CheckConstraint(
            _in_list("algorithm", PASSWORD_ALGORITHMS), name="user_credentials_algorithm_check"
        ),
    )


# --------------------------------------------------------------------------- #
# Roles and permissions
# --------------------------------------------------------------------------- #


class Role(Base):
    """A named role. ``rank`` orders roles for display, never for authorisation."""

    __tablename__ = "roles"

    role_key: Mapped[str] = mapped_column(Text, primary_key=True)
    title_ru: Mapped[str] = mapped_column(Text, nullable=False)
    description_ru: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    rank: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    is_system: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    permissions: Mapped[list["RolePermission"]] = relationship(
        back_populates="role", cascade="all, delete-orphan", passive_deletes=True
    )


class Permission(Base):
    """A single checkable capability, e.g. ``admin:panel`` or ``cabinet:teacher``."""

    __tablename__ = "permissions"

    permission_key: Mapped[str] = mapped_column(Text, primary_key=True)
    title_ru: Mapped[str] = mapped_column(Text, nullable=False)
    description_ru: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    category: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'general'"))
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    roles: Mapped[list["RolePermission"]] = relationship(
        back_populates="permission", cascade="all, delete-orphan", passive_deletes=True
    )


class RolePermission(Base):
    """Role -> permission edge. An explicit ``deny`` outranks every ``allow``."""

    __tablename__ = "role_permissions"

    role_key: Mapped[str] = mapped_column(
        Text, ForeignKey("roles.role_key", ondelete="CASCADE"), primary_key=True
    )
    permission_key: Mapped[str] = mapped_column(
        Text, ForeignKey("permissions.permission_key", ondelete="CASCADE"), primary_key=True
    )
    effect: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'allow'"))
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    role: Mapped["Role"] = relationship(back_populates="permissions")
    permission: Mapped["Permission"] = relationship(back_populates="roles")

    __table_args__ = (
        CheckConstraint(_in_list("effect", PERMISSION_EFFECTS), name="role_permissions_effect_check"),
        Index("idx_role_permissions_permission", "permission_key"),
    )


class RoleAssignment(Base):
    """A role held by a user **within a scope**.

    A teacher is not "a teacher": they are a teacher *of class 9IT at site
    Novaya Zvezda of school 2070*. The scope columns are real foreign keys, so
    an assignment can never point at a class that does not exist, and the CHECK
    constraint makes the scope type and the filled-in scope column agree.
    """

    __tablename__ = "role_assignments"

    assignment_id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, server_default=_UUID_PK)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False
    )
    role_key: Mapped[str] = mapped_column(Text, ForeignKey("roles.role_key"), nullable=False)
    scope_type: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'global'"))
    organization_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("organizations.organization_id"), nullable=True
    )
    school_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("schools.school_id"), nullable=True
    )
    site_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("school_sites.site_id"), nullable=True
    )
    class_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("school_classes.class_id"), nullable=True
    )
    subject: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    granted_by: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    granted_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())
    expires_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    revoked_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    revoked_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    user: Mapped["User"] = relationship(back_populates="role_assignments")

    __table_args__ = (
        CheckConstraint(_in_list("scope_type", SCOPE_TYPES), name="role_assignments_scope_type_check"),
        CheckConstraint(
            "(scope_type = 'global'::text AND organization_id IS NULL AND school_id IS NULL "
            "AND site_id IS NULL AND class_id IS NULL) "
            "OR (scope_type = 'organization'::text AND organization_id IS NOT NULL) "
            "OR (scope_type = 'school'::text AND school_id IS NOT NULL) "
            "OR (scope_type = 'site'::text AND site_id IS NOT NULL) "
            "OR (scope_type = 'class'::text AND class_id IS NOT NULL)",
            name="role_assignments_scope_shape_check",
        ),
        Index("idx_role_assignments_user", "user_id"),
        Index("idx_role_assignments_school", "school_id"),
        Index("idx_role_assignments_organization", "organization_id"),
        Index("idx_role_assignments_class", "class_id"),
        Index(
            "uq_role_assignments_active",
            "user_id",
            "role_key",
            "scope_type",
            text("COALESCE(organization_id, ''::text)"),
            text("COALESCE(school_id, ''::text)"),
            text("COALESCE(site_id, ''::text)"),
            text("COALESCE(class_id, ''::text)"),
            text("COALESCE(subject, ''::text)"),
            unique=True,
            postgresql_where=text("revoked_at IS NULL"),
        ),
    )


# --------------------------------------------------------------------------- #
# Sessions
# --------------------------------------------------------------------------- #


class UserSession(Base):
    """A login session. ``session_id`` keeps the existing 32-hex format."""

    __tablename__ = "user_sessions"

    session_id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False
    )
    role_key: Mapped[Optional[str]] = mapped_column(Text, ForeignKey("roles.role_key"), nullable=True)
    access_jti: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    access_expires_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    expires_at: Mapped[datetime] = mapped_column(TZ, nullable=False)
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())
    last_seen_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    revoked: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    revoked_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    revoked_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    device_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    ip_hash: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    user_agent_hash: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    user: Mapped["User"] = relationship(back_populates="sessions")
    refresh_tokens: Mapped[list["RefreshToken"]] = relationship(
        back_populates="session", cascade="all, delete-orphan", passive_deletes=True
    )

    __table_args__ = (
        Index("idx_user_sessions_user", "user_id"),
        Index("idx_user_sessions_expires", "expires_at"),
        Index("idx_user_sessions_access_jti", "access_jti"),
    )


class RefreshToken(Base):
    """One link of a refresh-token rotation chain.

    Only the SHA-256 of the token is stored. ``replaced_by_token_id`` makes
    replay detectable: presenting a token that already has a successor means the
    chain forked, and the whole session is revoked.
    """

    __tablename__ = "refresh_tokens"

    token_id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, server_default=_UUID_PK)
    session_id: Mapped[str] = mapped_column(
        Text, ForeignKey("user_sessions.session_id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[str] = mapped_column(Text, nullable=False)
    issued_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())
    expires_at: Mapped[datetime] = mapped_column(TZ, nullable=False)
    used_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    replaced_by_token_id: Mapped[Optional[str]] = mapped_column(
        UUID(as_uuid=False), ForeignKey("refresh_tokens.token_id", ondelete="SET NULL"), nullable=True
    )
    revoked_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)

    session: Mapped["UserSession"] = relationship(
        back_populates="refresh_tokens", foreign_keys=[session_id]
    )

    __table_args__ = (
        UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
        Index("idx_refresh_tokens_session", "session_id"),
    )


# --------------------------------------------------------------------------- #
# Consents and family links
# --------------------------------------------------------------------------- #


class Consent(Base):
    """A recorded consent, always tied to a document version and a moment.

    ``accepted_by_user_id`` differs from ``user_id`` when a parent consents on
    behalf of a child -- which is exactly the case the law cares about.
    """

    __tablename__ = "consents"

    consent_id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, server_default=_UUID_PK)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False
    )
    consent_type: Mapped[str] = mapped_column(Text, nullable=False)
    document_version: Mapped[str] = mapped_column(Text, nullable=False)
    accepted_at: Mapped[datetime] = mapped_column(TZ, nullable=False)
    accepted_by_user_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="SET NULL"), nullable=True
    )
    subject_role: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    revoked_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    evidence: Mapped[Any] = mapped_column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    user: Mapped["User"] = relationship(back_populates="consents", foreign_keys=[user_id])

    __table_args__ = (
        CheckConstraint(_in_list("consent_type", CONSENT_TYPES), name="consents_type_check"),
        UniqueConstraint(
            "user_id", "consent_type", "document_version", name="uq_consents_user_type_version"
        ),
        Index("idx_consents_user", "user_id"),
    )


class ParentChildLink(Base):
    """Parent -> child relation, including the pending invitation state."""

    __tablename__ = "parent_child_links"

    link_id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, server_default=_UUID_PK)
    parent_user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False
    )
    child_user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False
    )
    relation: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'parent'"))
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'pending'"))
    invite_code: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    invited_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    confirmed_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    revoked_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    __table_args__ = (
        CheckConstraint(_in_list("status", LINK_STATUSES), name="parent_child_links_status_check"),
        CheckConstraint(
            "parent_user_id <> child_user_id", name="parent_child_links_distinct_check"
        ),
        UniqueConstraint("parent_user_id", "child_user_id", name="uq_parent_child_links_pair"),
        UniqueConstraint("invite_code", name="uq_parent_child_links_invite_code"),
        Index("idx_parent_child_links_child", "child_user_id"),
    )


# --------------------------------------------------------------------------- #
# Entitlements and feature flags
# --------------------------------------------------------------------------- #


class UserEntitlement(Base):
    """Mutable per-user counters that are not derivable from grants."""

    __tablename__ = "user_entitlements"

    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), primary_key=True
    )
    ai_quota_left: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    ai_quota_reset_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    updated_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    __table_args__ = (
        CheckConstraint("ai_quota_left >= 0", name="user_entitlements_quota_check"),
    )


class UserEntitlementItem(Base):
    """One effective plan / module / feature held by a user.

    Normalised on purpose: the JSON state kept three parallel arrays per user
    with no way to say where an entry came from or when it expires. Here every
    entry names its source grant, so revoking a licence has a defined effect.
    """

    __tablename__ = "user_entitlement_items"

    item_id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, server_default=_UUID_PK)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    value: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'manual'"))
    grant_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("access_grants.grant_id", ondelete="SET NULL"), nullable=True
    )
    starts_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    expires_at: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    __table_args__ = (
        CheckConstraint(_in_list("kind", ENTITLEMENT_KINDS), name="user_entitlement_items_kind_check"),
        CheckConstraint(
            _in_list("source", ENTITLEMENT_SOURCES), name="user_entitlement_items_source_check"
        ),
        UniqueConstraint("user_id", "kind", "value", name="uq_user_entitlement_items"),
        Index("idx_user_entitlement_items_user", "user_id"),
        Index("idx_user_entitlement_items_grant", "grant_id"),
    )


class FeatureFlag(Base):
    """Registry of feature flags. A flag that is not registered is off."""

    __tablename__ = "feature_flags"

    flag_key: Mapped[str] = mapped_column(Text, primary_key=True)
    title_ru: Mapped[str] = mapped_column(Text, nullable=False)
    description_ru: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    overrides: Mapped[list["FeatureFlagOverride"]] = relationship(
        back_populates="flag", cascade="all, delete-orphan", passive_deletes=True
    )


class FeatureFlagOverride(Base):
    """Per-scope override of a flag. The narrowest matching scope wins."""

    __tablename__ = "feature_flag_overrides"

    override_id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, server_default=_UUID_PK)
    flag_key: Mapped[str] = mapped_column(
        Text, ForeignKey("feature_flags.flag_key", ondelete="CASCADE"), nullable=False
    )
    scope_type: Mapped[str] = mapped_column(Text, nullable=False)
    organization_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("organizations.organization_id", ondelete="CASCADE"), nullable=True
    )
    school_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("schools.school_id", ondelete="CASCADE"), nullable=True
    )
    site_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("school_sites.site_id", ondelete="CASCADE"), nullable=True
    )
    class_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("school_classes.class_id", ondelete="CASCADE"), nullable=True
    )
    user_id: Mapped[Optional[str]] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=True
    )
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False)
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    flag: Mapped["FeatureFlag"] = relationship(back_populates="overrides")

    __table_args__ = (
        CheckConstraint(
            _in_list("scope_type", FLAG_SCOPE_TYPES), name="feature_flag_overrides_scope_type_check"
        ),
        Index(
            "uq_feature_flag_overrides_scope",
            "flag_key",
            "scope_type",
            text("COALESCE(organization_id, ''::text)"),
            text("COALESCE(school_id, ''::text)"),
            text("COALESCE(site_id, ''::text)"),
            text("COALESCE(class_id, ''::text)"),
            text("COALESCE(user_id, ''::text)"),
            unique=True,
        ),
    )


class UserAppState(Base):
    """Client-owned state synced from a device: content versions, preferences.

    Genuinely schemaless -- the client decides what it stores -- so it is JSONB
    on purpose. Nothing in the access chain reads it.
    """

    __tablename__ = "user_app_state"

    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.user_id", ondelete="CASCADE"), primary_key=True
    )
    content_versions: Mapped[Any] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    preferences: Mapped[Any] = mapped_column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    updated_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())


# --------------------------------------------------------------------------- #
# Authentication throttling and audit
# --------------------------------------------------------------------------- #


class OtpChallenge(Base):
    """Outstanding phone one-time code. Keyed by the hash of the phone number."""

    __tablename__ = "otp_challenges"

    phone_hash: Mapped[str] = mapped_column(Text, primary_key=True)
    code_hash: Mapped[str] = mapped_column(Text, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(TZ, nullable=False)
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    locked_until: Mapped[Optional[datetime]] = mapped_column(TZ, nullable=True)
    created_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())


class AuthAttemptEvent(Base):
    """Append-only record of an authentication attempt, used for rate limiting.

    Only the hash of the identifier is stored: a rate-limit table must not
    become a directory of who tried to log in.
    """

    __tablename__ = "auth_attempt_events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    attempt_key: Mapped[str] = mapped_column(Text, nullable=False)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    result: Mapped[str] = mapped_column(Text, nullable=False)
    user_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    occurred_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())

    __table_args__ = (
        Index("idx_auth_attempt_events_key", "attempt_key", text("occurred_at DESC")),
    )


class AuthLockout(Base):
    """Active lockout for one attempt key. Mutable by design."""

    __tablename__ = "auth_lockouts"

    attempt_key: Mapped[str] = mapped_column(Text, primary_key=True)
    locked_until: Mapped[datetime] = mapped_column(TZ, nullable=False)
    reason: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    updated_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())


class AuditLogEntry(Base):
    """Append-only audit trail.

    ``denied_link`` names the link of the access chain that refused the request
    -- that is what makes an access decision explainable after the fact instead
    of "403 and good luck".
    """

    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    occurred_at: Mapped[datetime] = mapped_column(TZ, nullable=False, server_default=func.now())
    actor_user_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    actor_role: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    object_type: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    object_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    result: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'ok'"))
    denied_link: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    organization_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    school_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    site_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    class_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    request_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    correlation_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    details: Mapped[Any] = mapped_column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))

    __table_args__ = (
        CheckConstraint(_in_list("result", AUDIT_RESULTS), name="audit_log_result_check"),
        Index("idx_audit_log_occurred_at", text("occurred_at DESC")),
        Index("idx_audit_log_actor", "actor_user_id"),
        Index("idx_audit_log_action", "action"),
        Index("idx_audit_log_school", "school_id"),
    )
