import tempfile
import unittest
from pathlib import Path

from fastapi.testclient import TestClient

from app.main import app
from app.services import user_state_store as store


class AdminWebAppTest(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp_dir = tempfile.TemporaryDirectory()
        self._original_state_path = store.STATE_PATH
        store.STATE_PATH = Path(self._tmp_dir.name) / "user_state.json"
        self.client = TestClient(app)

    def tearDown(self) -> None:
        store.STATE_PATH = self._original_state_path
        self._tmp_dir.cleanup()

    def test_admin_web_assets(self) -> None:
        index = self.client.get("/api/v1/admin/web")
        self.assertEqual(index.status_code, 200, index.text)
        self.assertIn("Алхимик Web-кабинет", index.text)
        self.assertIn("/api/v1/admin/web/assets/app.js", index.text)
        self.assertIn("/api/v1/admin/web/assets/icon.png", index.text)
        self.assertIn("data-view=\"users\"", index.text)
        self.assertIn("data-view=\"schools\"", index.text)
        self.assertIn("data-view-content=\"audit\"", index.text)
        self.assertIn("btnBulkPreview", index.text)
        self.assertIn("btnUsersPrev", index.text)
        self.assertIn("btnAuditNext", index.text)
        self.assertIn("btnCreateUser", index.text)
        self.assertIn("btnGrantAccess", index.text)
        self.assertIn("accessSourceType", index.text)
        self.assertIn("accessSchool", index.text)
        self.assertIn("btnSchoolsOverview", index.text)
        self.assertIn("schoolCards", index.text)
        self.assertIn("adminLogin", index.text)
        self.assertIn("adminPassword", index.text)
        self.assertIn("btnAdminLogin", index.text)
        self.assertIn("btnSetRole", index.text)
        self.assertIn("newUserPlan", index.text)
        self.assertIn("newUserModule", index.text)
        self.assertIn("newUserPlanManual", index.text)
        self.assertIn("newUserModuleManual", index.text)
        self.assertIn("createUserResult", index.text)
        self.assertIn("data-view-content=\"security\"", index.text)
        self.assertIn("btnSecurity", index.text)
        self.assertIn("btnSecurityActions", index.text)
        self.assertIn("btnGoNoGo", index.text)
        self.assertIn("btnGoNoGoHistory", index.text)
        self.assertIn("goNoGoSummary", index.text)
        self.assertIn("goNoGoActionSummary", index.text)
        self.assertIn("goNoGoHistorySummary", index.text)
        self.assertIn("goNoGoHistoryTbody", index.text)
        self.assertIn("goNoGoGatesTbody", index.text)
        self.assertIn("btnMorningCheck", index.text)
        self.assertIn("btnIncidentCheck", index.text)
        self.assertIn("runbookActionStatus", index.text)
        self.assertIn("btnSecurityAutoRefresh", index.text)
        self.assertIn("btnSecurityResetFilters", index.text)
        self.assertIn("btnShortcuts", index.text)
        self.assertIn("shortcutsOverlay", index.text)
        self.assertIn("btnOpenGuide", index.text)
        self.assertIn("guideOverlay", index.text)
        self.assertIn("btnGuidePrint", index.text)
        self.assertIn("handoverTime", index.text)
        self.assertIn("handoverOutgoing", index.text)
        self.assertIn("handoverIncoming", index.text)
        self.assertIn("handoverIncidents", index.text)
        self.assertIn("handoverComment", index.text)
        self.assertIn("btnSaveHandover", index.text)
        self.assertIn("btnExportHandover", index.text)
        self.assertIn("btnArchiveHandover", index.text)
        self.assertIn("btnExportHandoverArchiveCsv", index.text)
        self.assertIn("securityActionsTbody", index.text)
        self.assertIn("restoreAction", index.text)
        self.assertIn("btnRestoreAction", index.text)
        self.assertIn("btnSecurityExport", index.text)
        self.assertIn("securityExportFormat", index.text)
        self.assertIn("securityExportMode", index.text)
        self.assertIn("securityDateFrom", index.text)
        self.assertIn("securityDateTo", index.text)
        self.assertIn("securityPreset", index.text)
        self.assertIn("btnApplyPeriod", index.text)
        self.assertIn("data-hint=", index.text)
        self.assertIn("securityAlertsSummary", index.text)
        self.assertIn("mobileReadinessSummary", index.text)
        self.assertIn("contentIngestionSummary", index.text)
        self.assertIn("btnContentQaSummary", index.text)
        self.assertIn("btnContentSourceSave", index.text)
        self.assertIn("btnContentBlockSave", index.text)
        self.assertIn("btnContentTransition", index.text)
        self.assertIn("contentQaEditStatus", index.text)
        self.assertIn("btnContentSourcesSearch", index.text)
        self.assertIn("btnContentBlocksSearch", index.text)
        self.assertIn("contentQaRegistryPanel", index.text)
        self.assertIn("contentSourcesTbody", index.text)
        self.assertIn("contentBlocksTbody", index.text)
        self.assertIn("btnContentHistoryLoad", index.text)
        self.assertIn("contentHistoryTbody", index.text)
        self.assertIn("v=20260520qa2", index.text)
        self.assertIn("contentQaTbody", index.text)
        self.assertIn("mobileSmokeStatus", index.text)
        self.assertIn("btnMobileReadiness", index.text)
        self.assertIn("btnMobileSmokeSave", index.text)
        self.assertIn("btnContentIngestion", index.text)
        self.assertIn("mobileSecuritySummary", index.text)
        self.assertIn("mobileSecChecks", index.text)
        self.assertIn("mobileSecTrend", index.text)
        self.assertIn("mobileCollapse", index.text)
        self.assertIn("data-mobile-collapse=", index.text)
        self.assertIn("securityAlertsTbody", index.text)
        self.assertIn("securityAlertCode", index.text)
        self.assertIn("securityAlertAckFilter", index.text)
        self.assertIn("securityAlertSeverityFilter", index.text)
        self.assertIn("btnSecurityAck", index.text)
        self.assertIn("btnSecurityUnack", index.text)
        self.assertIn("backupDryRunChecksTbody", index.text)
        self.assertIn("backupDryRunHistorySummary", index.text)
        self.assertIn("backupDryRunTrendSummary", index.text)
        self.assertIn("backupDryRunHistoryTbody", index.text)

        js = self.client.get("/api/v1/admin/web/assets/app.js")
        self.assertEqual(js.status_code, 200, js.text)
        self.assertIn("loadMatrix", js.text)
        self.assertIn("loadSchoolsOverview", js.text)
        self.assertIn("grantAccessForSelected", js.text)
        self.assertIn("loadSelectedUserAccesses", js.text)
        self.assertIn("switchView", js.text)
        self.assertIn("loadAudit", js.text)
        self.assertIn("runBulk", js.text)
        self.assertIn("readStateFromUrl", js.text)
        self.assertIn("writeStateToUrl", js.text)
        self.assertIn("createUser", js.text)
        self.assertIn("loginByPassword", js.text)
        self.assertIn("setRoleForSelected", js.text)
        self.assertIn("newUserPlan", js.text)
        self.assertIn("DEFAULT_ROLES", js.text)
        self.assertIn("Опции загружены с fallback ролями", js.text)
        self.assertIn("loadSecurity", js.text)
        self.assertIn("runMorningCheck", js.text)
        self.assertIn("runIncidentCheck", js.text)
        self.assertIn("loadGoNoGo", js.text)
        self.assertIn("renderGoNoGo", js.text)
        self.assertIn("loadGoNoGoHistory", js.text)
        self.assertIn("renderGoNoGoGates", js.text)
        self.assertIn("goNoGoActionSummary", js.text)
        self.assertIn("toggleSecurityAutorefresh", js.text)
        self.assertIn("openShortcutsModal", js.text)
        self.assertIn("openGuideModal", js.text)
        self.assertIn("openPrintableGuide", js.text)
        self.assertIn("initHandoverForm", js.text)
        self.assertIn("saveHandover", js.text)
        self.assertIn("archiveHandover", js.text)
        self.assertIn("exportHandoverArchiveCsv", js.text)
        self.assertIn("exportHandover", js.text)
        self.assertIn("loadMobileReadiness", js.text)
        self.assertIn("saveMobileSmoke", js.text)
        self.assertIn("smokeSla", js.text)
        self.assertIn("loadContentIngestion", js.text)
        self.assertIn("/admin/security/content-ingestion", js.text)
        self.assertIn("loadContentQaSummary", js.text)
        self.assertIn("/content/qa/summary", js.text)
        self.assertIn("saveContentSource", js.text)
        self.assertIn("saveContentBlock", js.text)
        self.assertIn("transitionContentBlock", js.text)
        self.assertIn("loadContentSources", js.text)
        self.assertIn("loadContentBlocks", js.text)
        self.assertIn("fillContentSourceForm", js.text)
        self.assertIn("fillContentBlockForm", js.text)
        self.assertIn("loadContentQaDashboard", js.text)
        self.assertIn("loadContentBlockHistory", js.text)
        self.assertIn("/events?limit=50", js.text)
        self.assertIn("content-qa-history", js.text)
        self.assertIn("/content/qa/sources", js.text)
        self.assertIn("/content/qa/blocks", js.text)
        self.assertIn("loadSecurityActions", js.text)
        self.assertIn("runBackupDryRun", js.text)
        self.assertIn("executeRestoreAction", js.text)
        self.assertIn("renderBackupDryRunStatus", js.text)
        self.assertIn("loadBackupDryRunHistory", js.text)
        self.assertIn("exportSecurityJson", js.text)
        self.assertIn("exportSecurityCsv", js.text)
        self.assertIn("exportSecurityByFormat", js.text)
        self.assertIn("mode=", js.text)
        self.assertIn("fromDate=", js.text)
        self.assertIn("toDate=", js.text)
        self.assertIn("securityStateKey", js.text)
        self.assertIn("sxm", js.text)
        self.assertIn("sfrom", js.text)
        self.assertIn("sack", js.text)
        self.assertIn("renderMobileSecuritySummary", js.text)
        self.assertIn("securityMobileState", js.text)
        self.assertIn("initMobileCollapses", js.text)
        self.assertIn("applySecurityPreset", js.text)
        self.assertIn("btnApplyPeriod", js.text)
        self.assertIn("loadSecurityAlerts", js.text)
        self.assertIn("ackSecurityAlert", js.text)
        self.assertIn("acked=", js.text)
        self.assertIn("severity=", js.text)

        css = self.client.get("/api/v1/admin/web/assets/styles.css")
        self.assertEqual(css.status_code, 200, css.text)
        self.assertIn(".heroIcon", css.text)
        self.assertIn(".hintable", css.text)
        self.assertIn(".mobileSecuritySummary", css.text)
        self.assertIn(".mobileCollapse", css.text)
        self.assertIn(".contentQaGrid", css.text)
        self.assertIn(".contentQaEditorGrid", css.text)
        self.assertIn(".contentQaRegistryPanel", css.text)
        self.assertIn(".contentQaRegistryGrid", css.text)
        self.assertIn("body.authorized .viewSection.authOnly", css.text)

        one_page = self.client.get("/api/v1/admin/web/assets/admin-one-page-ru-v3.html")
        self.assertEqual(one_page.status_code, 200, one_page.text)
        self.assertIn("One-Page", one_page.text)
        self.assertIn("Инциденты за смену", one_page.text)
        self.assertIn("ФИО дежурного", one_page.text)
        self.assertIn("handoverTime", one_page.text)
        self.assertIn("handoverOutgoing", one_page.text)
        self.assertIn("handoverIncoming", one_page.text)

        guide_txt = self.client.get("/api/v1/admin/web/assets/admin-manual-ru-v3.txt")
        self.assertEqual(guide_txt.status_code, 200, guide_txt.text)
        self.assertIn("Инструкция администратора", guide_txt.text)

        guide_docx = self.client.get("/api/v1/admin/web/assets/admin-manual-ru-v3.docx")
        self.assertEqual(guide_docx.status_code, 200, guide_docx.text)

        icon = self.client.get("/api/v1/admin/web/assets/icon.png")
        self.assertEqual(icon.status_code, 200, icon.text)


if __name__ == "__main__":
    unittest.main()
