import type { ApprovedStudentDashboardSource } from "../adapters/student-dashboard";

const assetBase = "/design-assets/student-dashboard/clean";
const approvedAssetBase = "/design-preview/student-dashboard";

export const approvedStudentDashboardSource: ApprovedStudentDashboardSource = {
  generatedAt: "2026-07-08T00:00:00+03:00",
  learner: {
    id: "student_demo_alina",
    name: "Алина",
    grade: "9 класс",
    school: "Школа 2070",
    avatarInitials: "А",
    avatarImage: `${assetBase}/icons/profile-placeholder.svg`,
    streakDays: 12,
  },
  topbar: {
    greeting: "Здравствуйте, Алина! 👋",
    subtitle: "Продолжим обучение с того места, где ты остановилась.",
    searchPlaceholder: "Поиск по темам, заданиям, курсам...",
    notificationCount: 6,
  },
  assets: {
    logo: "/design-assets/shared/logo/allchemist-mark.svg",
    chemistryHero: `${approvedAssetBase}/continue-visual.png`,
    liveLesson: `${approvedAssetBase}/lesson-visual.png`,
    lockedAnatomy: `${approvedAssetBase}/anatomy-preview.png`,
    assistantRobot: `${approvedAssetBase}/assistant-robot.png`,
  },
  sidebarItems: [
    { id: "home", label: "Главная", href: "#overview", icon: `${assetBase}/icons/nav-home.svg`, active: true, matchPaths: ["/design-preview/student-dashboard", "/dashboard/student"] },
    { id: "courses", label: "Мои курсы", href: "#courses", icon: `${assetBase}/icons/nav-courses.svg` },
    { id: "theory", label: "Теория", href: "#quick-access", icon: `${assetBase}/icons/nav-theory.svg` },
    { id: "tasks", label: "Задания", href: "#tasks", icon: `${assetBase}/icons/nav-tasks.svg` },
    { id: "labs", label: "Лаборатории", href: "#labs", icon: `${assetBase}/icons/nav-labs.svg` },
    {
      id: "visualization",
      label: "Визуализация",
      href: "#quick-access",
      icon: `${assetBase}/icons/nav-visualization.svg`,
      matchPaths: ["/modules/physics", "/modules/biology", "/modules/visualization"],
      children: [
        { id: "molecules", label: "3D-молекулы", href: "/modules/visualization/molecules", matchPaths: ["/modules/visualization/molecules"] },
        { id: "simulators", label: "Симуляторы", href: "/modules/physics", matchPaths: ["/modules/physics"] },
        { id: "microscope", label: "Микроскоп", href: "/modules/biology", matchPaths: ["/modules/biology"] },
        { id: "cell3d", label: "3D-клетка", href: "/modules/biology#cell", matchPaths: ["/modules/biology/cell"] },
        { id: "anatomy", label: "Анатомия", href: "/modules/biology#anatomy", matchPaths: ["/modules/biology/anatomy"] },
      ],
    },
    {
      id: "references",
      label: "Справочники",
      href: "#quick-access",
      icon: `${assetBase}/icons/nav-references.svg`,
      matchPaths: ["/reference"],
      children: [
        { id: "periodic", label: "Таблица элементов", href: "/reference/periodic-table", matchPaths: ["/reference/periodic-table"] },
        { id: "formulas", label: "Формулы", href: "/reference/formulas", matchPaths: ["/reference/formulas"] },
        { id: "laws", label: "Законы и константы", href: "/reference/laws", matchPaths: ["/reference/laws"] },
        { id: "reactions", label: "Реакции", href: "/reference/reactions", matchPaths: ["/reference/reactions"] },
      ],
    },
    { id: "exams", label: "Экзамены", href: "#quick-access", icon: `${assetBase}/icons/nav-exams.svg` },
    { id: "diagnostics", label: "Диагностика", href: "#weak-topics", icon: `${assetBase}/icons/nav-diagnostics.svg` },
    { id: "ai", label: "AI-наставник", href: "#assistant", icon: `${assetBase}/icons/nav-ai-mentor.svg` },
    { id: "progress", label: "Прогресс", href: "#progress", icon: `${assetBase}/icons/nav-progress.svg` },
    { id: "messages", label: "Сообщения", href: "#messages", icon: `${assetBase}/icons/nav-messages.svg`, badge: "3" },
    { id: "settings", label: "Настройки", href: "#settings", icon: `${assetBase}/icons/nav-settings.svg` },
  ],
  modules: [
    { id: "chemistry", title: "Химия", status: "active", progress: 72, completed: 84, total: 116 },
    { id: "physics", title: "Физика", status: "active", progress: 61, completed: 67, total: 110 },
    { id: "biology", title: "Биология", status: "active", progress: 58, completed: 53, total: 92 },
  ],
  currentCourses: [
    {
      id: "chem_reactions",
      subject: "chemistry",
      title: "Химические реакции",
      lessonTitle: "Типы и признаки",
      progress: 68,
      nextAction: "Продолжить",
      image: `${approvedAssetBase}/continue-visual.png`,
    },
    {
      id: "phys_motion",
      subject: "physics",
      title: "Механика",
      lessonTitle: "Равноускоренное движение",
      progress: 44,
      nextAction: "Открыть симулятор",
      image: `${approvedAssetBase}/lesson-visual.png`,
    },
    {
      id: "bio_cell",
      subject: "biology",
      title: "Клетка",
      lessonTitle: "Микроскопия растительной клетки",
      progress: 52,
      nextAction: "К микроскопу",
      image: `${assetBase}/thumbnails/popular-plant-cell.svg`,
    },
  ],
  liveLesson: {
    id: "live_newton",
    subject: "physics",
    label: "Ближайший live-урок",
    title: "Законы Ньютона. Применение в задачах",
    subtitle: "Разберём типовые ошибки и графики движения.",
    timeLabel: "Сегодня, 16:00 - 17:00",
    teacher: "Игорь Петрович",
    actionLabel: "Присоединиться",
    image: `${approvedAssetBase}/lesson-visual.png`,
  },
  aiRecommendations: [
    { id: "ai_valence", subject: "chemistry", title: "Повтори тему «Валентность»", subtitle: "Химия", icon: `${assetBase}/icons/quick-ai-mentor.svg` },
    { id: "ai_kinematics", subject: "physics", title: "Реши 3 задачи по кинематике", subtitle: "Физика", icon: `${assetBase}/icons/quick-tasks.svg` },
    { id: "ai_lab", subject: "chemistry", title: "Посмотри опыт «Реакция Zn + HCl»", subtitle: "Химия", icon: `${assetBase}/icons/quick-labs.svg` },
    { id: "ai_bio", subject: "biology", title: "Пройди диагностику по биологии", subtitle: "Биология", icon: `${assetBase}/icons/nav-diagnostics.svg` },
  ],
  quickAccess: [
    { id: "theory", label: "Теория", icon: `${assetBase}/icons/quick-theory.svg`, route: "/modules/theory", status: "available" },
    { id: "tasks", label: "Задания", icon: `${assetBase}/icons/quick-tasks.svg`, route: "/tasks", badge: "12", status: "new" },
    { id: "labs", label: "Лаборатории", icon: `${assetBase}/icons/quick-labs.svg`, route: "/labs", status: "available" },
    { id: "molecules", label: "3D-молекулы", icon: `${assetBase}/icons/quick-3d-molecules.svg`, route: "/modules/visualization/molecules", status: "available" },
    { id: "periodic", label: "Таблица элементов", icon: `${assetBase}/icons/quick-periodic-table.svg`, route: "/reference/periodic-table", status: "available" },
    { id: "simulators", label: "Симуляторы", icon: `${assetBase}/icons/quick-simulators.svg`, route: "/modules/physics", status: "available" },
    { id: "microscope", label: "Микроскоп", icon: `${assetBase}/icons/quick-microscope.svg`, route: "/modules/biology", status: "available" },
    { id: "exams", label: "Экзамены", icon: `${assetBase}/icons/quick-exams.svg`, route: "/exams", status: "available" },
    { id: "ai", label: "AI-наставник", icon: `${assetBase}/icons/quick-ai-mentor.svg`, route: "/assistant", status: "available" },
  ],
  recommendedLessons: [
    { id: "valence_repeat", subject: "chemistry", title: "Валентность и степень окисления", meta: "15 минут", reason: "закрывает слабое место" },
    { id: "kinematics_graph", subject: "physics", title: "Графики движения", meta: "12 минут", reason: "поможет в задачах" },
    { id: "mitosis_intro", subject: "biology", title: "Клеточное деление", meta: "10 минут", reason: "повтор перед тестом" },
  ],
  upcomingTasks: [
    { id: "task_chem_eq", subject: "chemistry", title: "Уравнения реакций", dueLabel: "Срок: завтра, 23:59", status: "todo" },
    { id: "task_phys_kin", subject: "physics", title: "Кинематика. Задачи 1-3", dueLabel: "Срок: 25 июн, 20:00", status: "in_progress" },
    { id: "task_bio_cell", subject: "biology", title: "Клеточное деление", dueLabel: "Срок: 27 июн, 18:00", status: "done" },
  ],
  weakTopics: [
    { id: "weak_valence", subject: "chemistry", title: "Валентность", actionLabel: "Повторить", reason: "низкая точность в последних заданиях" },
    { id: "weak_kinematics", subject: "physics", title: "Кинематика", actionLabel: "Повторить", reason: "ошибки в графиках движения" },
    { id: "weak_cell", subject: "biology", title: "Клеточное деление", actionLabel: "Повторить", reason: "требуется повтор перед тестом" },
    { id: "weak_atom", subject: "chemistry", title: "Строение атома", actionLabel: "Повторить", reason: "есть пробелы в диагностике" },
  ],
  popularContent: [
    { id: "popular_neutralization", subject: "chemistry", type: "experiment", title: "Реакция нейтрализации", meta: "Химия • Опыт", image: `${assetBase}/thumbnails/popular-neutralization.svg`, route: "/labs/neutralization" },
    { id: "popular_free_fall", subject: "physics", type: "simulation", title: "Свободное падение", meta: "Физика • Симуляция", image: `${assetBase}/thumbnails/popular-free-fall.svg`, route: "/modules/physics/free-fall" },
    { id: "popular_plant_cell", subject: "biology", type: "model", title: "Строение растительной клетки", meta: "Биология • 3D-модель", image: `${assetBase}/thumbnails/popular-plant-cell.svg`, route: "/modules/biology/plant-cell" },
  ],
  weeklyProgress: {
    title: "Твой прогресс за неделю",
    delta: "+12%",
    caption: "к прошлой неделе",
    explanation: "Считается по завершенным урокам, лабораторным и заданиям за последние 7 дней.",
    points: [
      { day: "Пн", value: 35 },
      { day: "Вт", value: 42 },
      { day: "Ср", value: 48 },
      { day: "Чт", value: 68 },
      { day: "Пт", value: 55 },
      { day: "Сб", value: 82 },
      { day: "Вс", value: 88 },
    ],
  },
  lockedFeature: {
    title: "3D-анатомия человека",
    requiredLicense: "Расширенная лицензия",
    subtitle: "Доступно в расширенной лицензии",
    actionLabel: "Узнать больше",
    image: `${approvedAssetBase}/anatomy-preview.png`,
  },
  labs: [
    { id: "lab_zn_hcl", subject: "chemistry", title: "Реакция цинка с HCl", status: "available", durationMin: 18, safety: "очки, перчатки" },
    { id: "sim_free_fall", subject: "physics", title: "Свободное падение", status: "available", durationMin: 12, safety: "безопасно" },
    { id: "micro_onion", subject: "biology", title: "Кожица лука под микроскопом", status: "locked", durationMin: 15, safety: "виртуальный образец" },
  ],
  aiHints: [
    { id: "hint_today", state: "hint", title: "Я рядом, если нужна подсказка", body: "Начни с валентности: это ускорит задания по реакциям.", cta: "Открыть подсказку", priority: "high" },
    { id: "hint_lab", state: "typing", title: "AI анализирует прогресс", body: "После урока по HCl я предложу короткую лабораторную проверку.", cta: "Показать план", priority: "normal" },
    { id: "hint_success", state: "success", title: "Серия занятий", body: "12 дней подряд: можно закрепить результат мини-тестом.", cta: "Мини-тест", priority: "normal" },
  ],
  achievements: [
    { id: "streak_12", title: "12 дней подряд", value: "12", tone: "success" },
    { id: "labs_4", title: "Лаборатории", value: "4", tone: "info" },
    { id: "accuracy_86", title: "Точность", value: "86%", tone: "warning" },
  ],
};
